name: Push Filtered
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
    tags:
      - 'v1.*'

jobs:
  filtered:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This ran on main or releases/* or tag v1.*"
